### ISSUE TITLE
第三章に関して質問です

### ISSUE THREAD

**Issue by sakanable** [uchan-nos/mikanos#10]
p.72l.4で「jnzはjump if not zeroの略で、ZFが0の場合にのみジャンプする」と書かれていますが、0でない場合にジャンプするの間違いではないでしょうか?

**Comment by uchan-nos** [comment]
ZFは、演算の結果が0なら1になる、というフラグなので、それで合っているのです。

**Comment by uchan-nos** [comment]
他の方が既存の質問を探すときにタイトルだけ見て概要が分かるように、
タイトルを変えさせていただきますね。

**Comment by uchan-nos** [comment]
@sakanable 今気づいたのですが、これmikanosリポジトリのissuesですね。書籍の質問はサポートサイト（os-from-zero）の方にお願いしますね。
