### ISSUE TITLE
PixelAt関数でposにマイナスの値を指定すると，フレームバッファ外のアドレスを返してしまう恐れがある．

### ISSUE THREAD

**Issue by rkarsnk** [uchan-nos/mikanos#22]
円描画の関数を書いてたときに気になったのですが，PixelAt関数でx座標とy座標を指定する際に座標にマイナスの値が含まれていた場合，フレームバッファを指すアドレスより小さいアドレスを算出してしまい，想定外のメモリ領域を書き換えてしまわないでしょうか？

https://github.com/uchan-nos/mikanos/blob/d4048a3a0eda64c6c533bcdba0e2f494d17c3b06/kernel/graphics.hpp#L105-L108

**Comment by uchan-nos** [comment]
はい。その通りです。
この関数に画面の範囲外を表す不正な座標を渡さないように注意してください。

関数の中で引数チェックするのか、関数の呼び出し側でチェックするのか、
というのは設計方針でどちらでも良いのです。
PixelAtに関しては、必要なら関数の呼び出し側で座標のチェックをする方針です。
