### ISSUE TITLE
ピクセル描画について

### ISSUE THREAD

**Issue by sz-shers** [uchan-nos/mikanos#32]
第４章のピクセル描画とmaka入門のp.102からp.106にあるプログラムについて質問です。
p.100のプログラムは実行と起動が問題なくできましたがp.102からp.106の部分がエラーが起きて実行できません。
具体的にいうと
makeとコンソールで入力すると
ld.lld: error: duplicate symbol: KernelMain
>>> defined at main.cpp:68
>>>            main.o:(KernelMain)
>>> defined at asmfunc.asm
>>>            asmfunc.o:(.text+0x7C)
make: *** [Makefile:27: kernel.elf] エラー 1
とでます。
多分僕の知識不足だと思いますがどうしたら実行できますか？
,

**Comment by uchan-nos** [comment]
@BD-sheres 
「ゼロからのOS自作入門」に関する質問でしょうか。
であれば、書籍のサポートサイト https://github.com/uchan-nos/os-from-zero/issues で質問してください。

その際、質問文の体裁をもう少し読みやすくお願いします。例えば……
- 「とでます。」のあたりが引用ぽくなっておりますが、これは引用ではなく、BD-sharesさんの発言ではないでしょうか。
- ソースコードを貼り付ける際は ``` と ``` で囲むとコードブロックになるので、綺麗に表示されます。お試しください。
