### ISSUE TITLE
[day08b] スタックの移動後のKernelMainNewStackの挙動

### ISSUE THREAD

**Issue by WinLinux1028** [uchan-nos/mikanos#38]
ブートローダーがKernelMainにフレームバッファとメモリマップのポインタを渡し､KernelMainはrspレジスタの変更でスタックの場所を変え､KernelMainNewStackを呼ぶという順で起動するようです
しかし､関数呼び出し時の引数はスタックを通して渡すはずなのに､KernelMainによってスタックの場所が変えられた後でもどういうわけかKernelMainNewStackから､KernelMainに渡した引数にアクセスできるようです

一体何故アクセスできてしまうんでしょうか...

**Comment by uchan-nos** [comment]
関数の引数はスタックではなくレジスタで渡されるからです。

**Comment by WinLinux1028** [comment]
ありがとうございます
どうやらスタック渡しになるのはレジスタで引数を渡しきれない場合のようですね
