### ISSUE TITLE
library.cのコミットし忘れ

### ISSUE THREAD

**Issue by tomiy-tomiylab** [uchan-nos/mikanos#56]
commit 204fa0e8200f52be61e6ae75bf82d219fd460b5cでmainがintを返せるようにapps/Makefile.elfappにlibrary.oをリンクして、--entry mainを削除されてますが、このコミットでビルドしようとすると、「make: *** No rule to make target '../library.o', needed by 'blocks'.  Stop. 」と怒られます。
おそらく、library.cのコミットを忘れてませんか？

library.cの中身は以下のようなコードですよね？
void _start(){
    int ret = main();
    exit(ret);
}

**Comment by uchan-nos** [comment]
こちらで解決 https://github.com/uchan-nos/mikanos/commit/30bf64c42e6070434c7ca0671def115c0ad2d048
