### ISSUE TITLE
ExitBootServicesの仕様による問題

### ISSUE THREAD

**Issue by HonokaNo** [uchan-nos/mikanos#8]
小さい問題ですが、ExitBootServicesのあとはSystemTable->ConOutがNULLになるっぽいです。(原文:On success, several fields of the EFI 
System Table should be set to NULL. These include ConsoleInHandle, ConIn, ConsoleOutHandle, ConOut, 
StandardErrorHandle, StdErr, and BootServicesTable.  221ページ 4行目)
そのため
https://github.com/uchan-nos/mikanos/blob/59251b6d0eb76f6e21b164cae91eb28cdad55a8e/MikanLoaderPkg/Main.c#L434
の部分のPrintは表示されません。
ExitBootServicesより先に実行させたほうがいいかと思われます。

**Comment by uchan-nos** [comment]
@HonokaNo 
報告ありがとうございます。
妥当なご指摘です。プルリクいただけたら取り込みますが、どうしますか？

**Comment by HonokaNo** [comment]
とりあえず修正でコードを書きましたが、どうやってプルリクをするのかよくわかっていません。
申し訳ないですがご教授願えないでしょうか

**Comment by uchan-nos** [comment]
大雑把な手順としては
1. リポジトリをForkする
2. Forkしたリポジトリに修正をコミットする
3. GitHubの画面からプルリクエストを出す

という感じなのですが、これだけじゃ分からないですよね……
詳しく説明するのはちょっと大変ですが、やる価値はあると思うので、しばらく（何日か）待っていただけますか？

**Comment by HonokaNo** [comment]
すみません。commitまではできたのですが、pushで403みたいなのです。
それでヒントをもらいたいです。

**Comment by uchan-nos** [comment]
Forkしたリポジトリにcommitしましたか？
単にCloneしたリポジトリにしてませんか？

**Comment by HonokaNo** [comment]
forkがよく分かってないのでそれかもしれません。
調べてきます。

**Comment by HonokaNo** [comment]
プルリクできました。
失礼しました。

**Comment by uchan-nos** [comment]
一応、プルリクの仕方をドキュメントにまとめました。ご参考までに。
https://github.com/uchan-nos/mikanos/blob/master/docs/how-to-send-pull-request.md
